### ISSUE TITLE
Wiki vs Docs, and plans for wiki

### ISSUE THREAD

**Issue by rpetit3** [turtlecoin/turtlecoin-docs#11]
So it looks like there's a lot of overlap between the docs repo and the wiki. Will the docs repo eventually be merged into the wiki or does it serve a different purpose?

Also, what is the plan for the wiki? Is it to remain a GitHub wiki or are you open to converting it to something like [readthedocs](https://readthedocs.org/), [slate](https://github.com/lord/slate), [mkdocs](http://www.mkdocs.org/), etc...?

**Comment by RocksteadyTC** [comment]
I am all for killing one of them and making it just one big thing.

**Comment by BebopTC** [comment]
Plan was for this to be *THE* repo for docs. @ZedPea had started work on the 'docs' repo and I didn't want to get in his way or step on his toes but he (i believe) is on board as well. so far most stuff has been merged but I think some new stuff was added/pushed to the 'docs' repo since.

I have been pulled away a bit the past couple of days but finishing up the organization of this as at the top of my list. I would request new additions be added to *this* repo in the form of PR or Issue w/ request for specific change/additions. I can give @ZedPea write/push rights to this repo to help things move along

**Comment by BebopTC** [comment]
Also to answer the 2nd part of your question @rpetit3, the docs shall continue to be written in markdown. 

The github 'wiki' feature on any repo is just a magic 2nd repo with name git@github.com:foo/bar.wiki.git that generates a 'wiki' style layout via the markdown files in the repo. So we can push this repo to it's *own* .wiki.git remote so that the markdown content is built onto the 'wiki' tab on github, as well as to the turtlecoin/turtlecoin.wiki.git so it is synced up on the 'wiki' of the turtlecoin core repo.

Nice thing about that is tools like slate and mkdocs pretty much do the same thing, parse markdown and build new layouts, so we can reuse the *same* repo for any other targets. If you're interested in playing with mkdocs or slate, feel free to mess around with it and then we can talk about setting up an automatic build to push it to, for instance, a github page or whatever to host the prettified docs.

**Comment by RocksteadyTC** [comment]
@ac1984 I'd like you to be included in this

**Comment by rpetit3** [comment]
I second @ac1984 I think his project would fit perfectly here

**Comment by ac1984** [comment]
@rpetit3 Thanks

Linking this discussion with my mine -  https://github.com/turtlecoin/meta/issues/58#issue-296217351.

**Comment by ZedPea** [comment]
I agree this should be the definitive repo for documentation, then we can link it on the main website and people can find all the stuff they need to know on the sidebar whilst reading the "Get started" or "Get mining" page. At the moment I'm just pushing my FAQ to both because it would seem odd to not.

I think we just need to get started on filling out all the content in the wiki outline then we can retire docs.

**Comment by SoreGums** [comment]
so what is the preferred way to do things?

I was on my phone yesterday when I did the #33 changes and now I'm on desktop I see I edited the files in the repo and not the magic 2nd wiki repo.

**Comment by BebopTC** [comment]
You're doing it correctly @SoreGums - i.e. PR to this repo. For the moment i have to manually push to the live wiki, so be sure to @ me in doscord to get my attention  :)

**Comment by SoreGums** [comment]
ok - further to this in terms of how to contribute changes.

I'm WIP on a guide [1] to follow for those new to how git works.
as can be seen following the overhaul discussions, if you don't know git it is difficult.
the guide will hopefully get people over the how-to-git-to-contribute-prs-for-docs hump

[1] https://github.com/SoreGums/turtlecoin-wiki/blob/how-to-contribute-to-wiki/guides/How-to-contribute-to-the-TurtleCoin-wiki.md

**Comment by Sajo8** [comment]
As I understand it, this issue is resolved? All docs are now in this repo (turtlecoin-docs). They are hosted on docs.turtlecoin.lol. 

The api-docs' frontend is on a different repo (docs still in this repo), and I believe @SoreGums was looking at iframing it in another page on docs.turtlecoin.lol

While not completely clear, the questions in this issue seem to be answered/resolved. Possibly it could be altered so that the current uncertainty is addressed?

**Comment by SoreGums** [comment]
All references to wiki ought to be changed to docs.

I've kept a copy of the guide linked above and am updating it to fit the new way.

This issue looks resolved to me.
