### ISSUE TITLE
sajodocs' compatibility with turtlecoin-docs

### ISSUE THREAD

**Issue by Sajo811** [turtlecoin/turtlecoin-docs#187]
So I've been playing around with the idea of building sajodocs from turtlecoin-docs

So it requires strict md; i made a nice contributing guidelines thing on the repo to help
So bear with me here;
We can take those and add it as a CONTRIBUTING.md file here in turtlecoin-docs
everyone writes according to those rules
mkdocs is compatible with that
it builds from that
everyone's happy
one source of truth has everything
hooray

and how about the github wiki?
links become borken right
i dont think so
heres a test repo i made: https://github.com/Sajo811/turtledocs/wiki
play around with it
example: https://i.imgur.com/7velVCZ.gifv

u know that the mining guide isnt in the same folder as the getting started guide
but it works
yay
so
i was thinking

is it acceptable that everyone writes according to the rules
we build from the one source of trooth
and if we try to use the github wiki then we get an error if we try to visit a guide not in the same folder; but it still works
thots?
cc @ar-x @SoreGums @ZedPea @RocksteadyTC

**Comment by Sajo811** [comment]
update: seems some links dont work actly [(step 4 here)](https://github.com/Sajo811/turtledocs/wiki/XMR-Stak-Linux-Guide#xmr-stak-setup-and-configuration)

so i guess quesion becomes: is it fine if some links dont work on the github wiki but mkdocs wiki builds straight from one source of truth

**Comment by Sajo811** [comment]
and in some cases images too kek

**Comment by SoreGums** [comment]
If you want this automatic. You write a translator from GHFM to strict Markdown.

Or you use a different renderer that doesn't need strict markdown.

Or you figure out the all in one frontend and do that.

There isn't really an option of changing the current thing to strict markdown and breaking the current thing. The only way this becomes a thing is if the all in one front end route is done, because then it doesn't matter that github wiki rendering doesn't work as it is replaced.

Please recognise why I'm saying the above and figure out a plan that fits what is required. The why is simple, while you are keen today, tomorrow you might not be, this project will be here tomorrow even if you aren't. What does or doesn't happen is for the project rather than the whims of an individual.

**Comment by ZedPea** [comment]
Well, you worded that a lot better than I was going to. +1.

**Comment by Sajo811** [comment]
This looked promising: http://pandoc.org but it's broken, both 2 and fro

I guess I'll close it then; we can work on this for the custom wiki 
https://github.com/turtlecoin/meta/issues/98
https://github.com/turtlecoin/meta/issues/102
